// Code generated by command: go run main.go -out ../kernels_amd64.s -stubs ../kernels_stub_amd64.go -pkg simd. DO NOT EDIT.

//go:build !purego

package simd

// swapRB32SSE swaps R<->B in pixels RGBA pixels (pixels must be a multiple of 4) using SSSE3.
//
//go:noescape
func swapRB32SSE(dst *byte, src *byte, pixels int)

// swapRB32AVX2 swaps R<->B in pixels RGBA pixels (pixels must be a multiple of 8) using AVX2.
//
//go:noescape
func swapRB32AVX2(dst *byte, src *byte, pixels int)

// bgrToRGBASSE converts pixels BGR pixels to RGBA (alpha 0xff) using SSSE3; pixels must be a multiple of 4 and the source must hold 16 readable bytes per group.
//
//go:noescape
func bgrToRGBASSE(dst *byte, src *byte, pixels int)

// rgbaToBGRSSE converts pixels RGBA pixels to BGR using SSSE3; pixels must be a multiple of 4 and the destination must hold 16 writable bytes per group.
//
//go:noescape
func rgbaToBGRSSE(dst *byte, src *byte, pixels int)
