// Code generated by command: go run main.go -out ../kernels_amd64.s -stubs ../kernels_stub_amd64.go -pkg simd. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

DATA swapRB32Mask16<>+0(SB)/16, $"\x02\x01\x00\x03\x06\x05\x04\a\n\t\b\v\x0e\r\f\x0f"
GLOBL swapRB32Mask16<>(SB), RODATA|NOPTR, $16

DATA swapRB32Mask32<>+0(SB)/32, $"\x02\x01\x00\x03\x06\x05\x04\a\n\t\b\v\x0e\r\f\x0f\x02\x01\x00\x03\x06\x05\x04\a\n\t\b\v\x0e\r\f\x0f"
GLOBL swapRB32Mask32<>(SB), RODATA|NOPTR, $32

DATA bgrToRGBAShuf<>+0(SB)/16, $"\x02\x01\x00\x80\x05\x04\x03\x80\b\a\x06\x80\v\n\t\x80"
GLOBL bgrToRGBAShuf<>(SB), RODATA|NOPTR, $16

DATA bgrToRGBAAlpha<>+0(SB)/16, $"\x00\x00\x00\xff\x00\x00\x00\xff\x00\x00\x00\xff\x00\x00\x00\xff"
GLOBL bgrToRGBAAlpha<>(SB), RODATA|NOPTR, $16

DATA rgbaToBGRShuf<>+0(SB)/16, $"\x02\x01\x00\x06\x05\x04\n\t\b\x0e\r\f\x80\x80\x80\x80"
GLOBL rgbaToBGRShuf<>(SB), RODATA|NOPTR, $16

// func swapRB32SSE(dst *byte, src *byte, pixels int)
// Requires: SSE2, SSSE3
TEXT ·swapRB32SSE(SB), NOSPLIT, $0-24
	MOVQ  dst+0(FP), AX
	MOVQ  src+8(FP), CX
	MOVQ  pixels+16(FP), DX
	MOVOU swapRB32Mask16<>+0(SB), X0

loop:
	CMPQ   DX, $0x04
	JL     done
	MOVOU  (CX), X1
	PSHUFB X0, X1
	MOVOU  X1, (AX)
	ADDQ   $0x10, CX
	ADDQ   $0x10, AX
	SUBQ   $0x04, DX
	JMP    loop

done:
	RET

// func swapRB32AVX2(dst *byte, src *byte, pixels int)
// Requires: AVX, AVX2
TEXT ·swapRB32AVX2(SB), NOSPLIT, $0-24
	MOVQ    dst+0(FP), AX
	MOVQ    src+8(FP), CX
	MOVQ    pixels+16(FP), DX
	VMOVDQU swapRB32Mask32<>+0(SB), Y0

loop:
	CMPQ    DX, $0x08
	JL      done
	VMOVDQU (CX), Y1
	VPSHUFB Y0, Y1, Y1
	VMOVDQU Y1, (AX)
	ADDQ    $0x20, CX
	ADDQ    $0x20, AX
	SUBQ    $0x08, DX
	JMP     loop

done:
	VZEROUPPER
	RET

// func bgrToRGBASSE(dst *byte, src *byte, pixels int)
// Requires: SSE2, SSSE3
TEXT ·bgrToRGBASSE(SB), NOSPLIT, $0-24
	MOVQ  dst+0(FP), AX
	MOVQ  src+8(FP), CX
	MOVQ  pixels+16(FP), DX
	MOVOU bgrToRGBAShuf<>+0(SB), X0
	MOVOU bgrToRGBAAlpha<>+0(SB), X1

loop:
	CMPQ   DX, $0x04
	JL     done
	MOVOU  (CX), X2
	PSHUFB X0, X2
	POR    X1, X2
	MOVOU  X2, (AX)
	ADDQ   $0x0c, CX
	ADDQ   $0x10, AX
	SUBQ   $0x04, DX
	JMP    loop

done:
	RET

// func rgbaToBGRSSE(dst *byte, src *byte, pixels int)
// Requires: SSE2, SSSE3
TEXT ·rgbaToBGRSSE(SB), NOSPLIT, $0-24
	MOVQ  dst+0(FP), AX
	MOVQ  src+8(FP), CX
	MOVQ  pixels+16(FP), DX
	MOVOU rgbaToBGRShuf<>+0(SB), X0

loop:
	CMPQ   DX, $0x04
	JL     done
	MOVOU  (CX), X1
	PSHUFB X0, X1
	MOVOU  X1, (AX)
	ADDQ   $0x10, CX
	ADDQ   $0x0c, AX
	SUBQ   $0x04, DX
	JMP    loop

done:
	RET
